spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysq.l.jdbc.Driver
    password: adminwinter
    url: jdbc:mysql://127.0.0.1/product?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true
env: 
  test
