spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: adminwinter
    url: jdbc:mysql://127.0.0.1/product?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.99.100
    username: guest
    password: guest
    port: 5672
